"""Create Game Model

Revision ID: aacdc327fbfa
Revises: c66b1e5a558f
Create Date: 2023-09-01 12:47:07.090803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aacdc327fbfa'
down_revision = 'c66b1e5a558f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
