"""Add Review Model

Revision ID: d83b83519f7e
Revises: aacdc327fbfa
Create Date: 2023-09-01 12:47:55.080735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83b83519f7e'
down_revision = 'aacdc327fbfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
